include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO tschw/AntTweakBar
    REF 4ff73b96515164cbe66b484022e56e771ea6c224 # current master
    SHA512 7bc171c3f52fba0be3a733657de93a43cbcee1e9c9a4ab5f82af0f1ddcf247136a5f780adc89436edfb89545fc5c41563fa7785fe1c7e0a26f8eddb4a5b46bb8
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DATB_BUILD_EXAMPLES=OFF
        -DATB_D3D11_FXC=OFF
        -DATB_EVENT_HANDLER_GLFW=OFF
        -DATB_EVENT_HANDLER_GLFW3=ON
        -DATB_EVENT_HANDLER_GLUT=OFF
        -DATB_EVENT_HANDLER_SDL12=OFF
        -DATB_EVENT_HANDLER_SDL13=OFF
        -DATB_EVENT_HANDLER_SDL20=OFF
        -DATB_EVENT_HANDLER_SFML=OFF
        -DATB_EVENT_HANDLER_WINDOWS=OFF
        -DATB_EVENT_HANDLER_X11=OFF
        -DATB_GUIRENDERER_USE_CORE_GL=ON
        -DATB_GUIRENDERER_USE_D3D10=OFF
        -DATB_GUIRENDERER_USE_D3D11=OFF
        -DATB_GUIRENDERER_USE_D3D9=OFF
        -DATB_GUIRENDERER_USE_LEGACY_GL=OFF
        -DBUILD_SHARED_LIBS=OFF
        #-DCMAKE_CONFIGURATION_TYPES="Debug;Release"
)

vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/AntTweakBar)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
if(NOT (NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore") AND NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/share/anttweakbar)
endif()

# Handle copyright
file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/anttweakbar RENAME copyright)